title: Alexandre Camarão
author:
  name: Ricardo Quintas                      # Default author name 
  email: 'rqcenter-web@yahoo.com'                   # Default author email
  copyright: "©2015 Ricardo Quintas"
  url: http://www.ricardoquintas.com
  url_name: ricardoquintas.com 
taxonomies: [category,tag]                  # Arbitrary list of taxonomy types
blog:
  route: '/blog'                            # Route to blog
metadata:
    description: 'My Deliver Site'             # Site description
summary:
  size: 300                                 # Maximum length of summary (characters)
routes:
  /artwork: '/artwork/drawings'             # ZRQ: This is just to invalidate the "artwork" page. There's nothing there
  /exhibitions: '/exhibitions/solo'             # ZRQ: This is just to invalidate the "exhibitions" page. There's nothing there  
  # /something/else: '/'         # Alias for /blog/sample-3
  # /another/one/here: '/blog/sample-3'       # Another alias for /blog/sample-3
  # /new/*: '/blog/*'                         # Wildcard any /new/my-page URL to /blog/my-page Route



